services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app:delegated
  database:
    image: postgres:17.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=123456abcdef
volumes:
  db_data:
