services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app:delegated
      - gem_cache:/usr/local/bundle/gems
    command: /bin/sh -c "while sleep 1000; do :; done"
  database:
    image: postgres:17.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=123456abcdef
volumes:
  gem_cache:
  db_data:
